server {
  listen 80;
  server_name angels-shop.ru www.angels-shop.ru;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  server_name angels-shop.ru www.angels-shop.ru;
  
  ssl_certificate /etc/letsencrypt/live/angels-shop.ru/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/angels-shop.ru/privkey.pem;
  
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;
  
  # location / {
  #   set $fe_app "angels-shop-fe-app:3000";
  #   proxy_pass http://$fe_app/;

  #   proxy_set_header Host $host;
  #   proxy_set_header X-Real-IP $remote_addr;
  #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #   proxy_set_header X-Forwarded-Proto $scheme;
  # }
  
  location /api/ {
    set $be_app "angels-shop-be-app:3000";
    proxy_pass http://$be_app/api/;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /api;
  }
}